services:
  questdb:
    image: questdb/questdb:8.1.0
    expose:
      - "9000"
    ports:
      - "19000:9000"
    environment:
      - QDB_LINE_DEFAULT_PARTITION_BY=YEAR
  kafka:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
  producer:
    image: kafka-questdb-connector-samples-faker-generator
    build:
      dockerfile: Dockerfile-App
    depends_on:
      - kafka
    links:
      - kafka:kafka
      - questdb:questdb
  connect:
    image: kafka-questdb-connector-samples-connect
    build:
      dockerfile: ./Dockerfile-Connect
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    links:
      - kafka:kafka
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
      CONNECT_GROUP_ID: "default"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-storage-topic"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-config-topic"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status-topic"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"