version: '2.1'
services:
  questdb:
    image: questdb/questdb:6.6.1
    expose:
      - "9009"
    ports:
      - "19000:9000"
    environment:
      - JAVA_OPTS=-Djava.locale.providers=JRE,SPI
      - QDB_LINE_DEFAULT_PARTITION_BY=YEAR
      - QDB_PG_SELECT_CACHE_ENABLED=false
  zookeeper:
    image: zookeeper:3.6.2
    ports:
      - "2181:2181"
  grafana:
    image: grafana/grafana-oss:9.2.1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    depends_on:
      - questdb
    links:
      - questdb:questdb
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=quest
        - GF_SECURITY_ADMIN_USER=admin
        - GF_USERS_ALLOW_SIGN_UP=false
        - GF_USERS_ALLOW_ORG_CREATE=false
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
        - GF_AUTH_ANONYMOUS_ORG_ID=1
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "dbserver1.public.stock:1:1"
  postgres:
    image: debezium/postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  producer:
    image: kafka-questdb-connector-samples-stocks-generator
    build:
      dockerfile: Dockerfile-App
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres:postgres
  connect:
    image: kafka-questdb-connector-samples-connect
    build:
      dockerfile: ./Dockerfile-Connect
      context: .
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    links:
      - kafka:kafka
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      CONFIG_STORAGE_TOPIC: "debezium_connect_config"
      OFFSET_STORAGE_TOPIC: "debezium_connect_offsets"
      STATUS_STORAGE_TOPIC: "debezium_connect_status"
